api: "https://razod-whapi.glitch.me/users" # DO NOT CHANGE THIS UNLESS YOU KNOW WHAT YOU'RE DOING
message: "§7You were §bkicked for joining without whitelisting yourself.\nGo to §bhttps://razod-whapi.glitch.me §7to be whitelisted."